---
- include_vars: "main.yml"

- include_vars: "system.yml"
  when: "rbenv_env == 'system'"

- include: "system/install.yml"
  when: "rbenv_env == 'system'"

- include_vars: "user.yml"
  when: "rbenv_env == 'user'"

- include: "user/install.yml"
  when: "rbenv_env == 'user'"

- name: add rbenv initialization to profile
  template: >
    src=rbenv.sh.j2
    dest=/etc/profile.d/rbenv.sh
    owner=root
    group=root
    mode=0755
  sudo: true
