---
- name: set default-gems
  template: >
    src=../../templates/default-gems.j2
    dest={{ rbenv_root }}/default-gems
  sudo: true

- name: set gemrc
  copy: src=../../files/gemrc dest=/etc/gemrc
  sudo: true

- name: set vars
  copy: src=../../files/vars dest={{ rbenv_root }}/vars
  sudo: true
