- hosts: all
  vars_files:
    - defaults/main.yml
    - vars/main.yml
    - vars/test.yml
  pre_tasks:
    - apt: update_cache=yes

    - apt: name={{item}} state=installed
      with_items:
        - git
        - autoconf
        - binutils-doc
        - bison
        - build-essential
        - flex
        - gettext
        - ncurses-dev
  tasks:
    - include: tasks/main.yml
