---
- hosts: all
  remote_user: vagrant
  sudo: yes

  pre_tasks:
    - include: tasks/prepare.yml
    - include: tasks/remove-ruby.yml

  roles:
    - role: angstwad.docker_ubuntu
      when: '"docker" in roles'
    - role: ANXS.timezone
      timezone_zone: "{{ vars.timezone_zone }}"
    - role: ANXS.build-essential
    - role: ANXS.git
    - role: ANXS.cron
    - role: ANXS.utilities
      utilities_extras:
        - silversearcher-ag
    - role: nodesource.node
      when: '"nodejs" in roles'
    - role: ANXS.postgresql
      when: '"postgresql" in roles'
      postgresql_version: "{{ vars.postgresql_version }}"
      postgresql_ext_install_contrib: yes
    - role: DavidWittman.redis
      when: '"redis" in roles'
      redis_version: "{{ vars.redis_version }}"
    - role: ANXS.mysql
      when: '"mysql" in roles'
      mysql_root_password: "{{ vars.mysql_root_password }}"
      mysql_users: "{{ vars.mysql_users }}"
    - role: jdauphant.nginx
      when: '"nginx" in roles'
      nginx_sites: "{{ vars.nginx_sites }}"
      nginx_configs: "{{ vars.nginx_configs }}"
    - role: pablocrivella.rbenv
      when: '"rbenv" in roles'
      rbenv:
        env: user
        version: v0.4.0
        global: "{{ vars.ruby_version }}"
        rubies:
          - "{{ vars.ruby_version }}"
      rbenv_default_gems: "{{ vars.ruby_gems_default }}"
      rbenv_users:
        - name: vagrant
          home: /home/vagrant
    - role: josemrb.phpenv
      when: '"phpenv" in roles'

  post_tasks:
    - include: tasks/libmysqlclient.yml
      when: '"mysql" in roles'
    - include: tasks/libpq.yml
      when: '"postgresql" in roles'
    - include: tasks/libpcre3.yml
    - include: tasks/qt-webkit.yml
      when: '"rbenv" in roles'
