---
- hosts: all
  remote_user: vagrant
  sudo: yes

  pre_tasks:
    - include: tasks/prep.yml

    - name: clean up | remove ruby
      apt: name=ruby state=absent

    - include: tasks/git.yml

    - include: tasks/nodejs.yml

  roles:
    - utilities

    - redis

    - role: mysql
      mysql_root_password: "{{ lookup('env', 'mysql_root_passwd') }}"
      mysql_users:
        - name: developer
          pass: "{{ lookup('env', 'mysql_developer_passwd') }}"
          host: "%"

    - role: rbenv
      sudo: no
      rbenv:
        env: user
        version: v0.4.0
        ruby_version: 2.1.2
      rbenv_users:
        - name: vagrant
          home: "/home/vagrant/"
